[workspace]
members = [
    "tcx-proto",
    "tcx-constants",
    "tcx-primitive",
    "tcx-crypto",
    "tcx-chain",
    "tcx-tron",
    "tcx-btc-fork",
    "tcx-bch",
    "tcx-ckb",
    "tcx-substrate",
    "tcx",
    "tcx-tezos",
    "tcx-tester",
]

