[package]
name = "tcx-tron"
version = "0.1.0"
authors = ["tyrone <2125081@qq.com>"]
edition = "2018"

[dependencies]
tcx-crypto = { path = "../tcx-crypto" }
tcx-chain = { path = "../tcx-chain" }
tcx-primitive = { path = "../tcx-primitive" }

hex-literal = "0.1.4"
keccak-hash = "0.2.0"
bitcoin = "0.18.0"
secp256k1 = "0.12"
tiny-bip39 = "0.6.0"
bitcoin_hashes = "0.3.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"
uuid = { version = "0.7", features = ["serde", "v4"] }
failure = "0.1.5"
num-bigint = "0.2"
num-traits = "0.2"
num-integer = "0.1"
byteorder = "1.3.2"
hex = "0.3.1"
