[package]
name = "tcx-bch"
version = "0.1.0"
authors = ["Neal Xu <imxuneal@gmail.com>"]
edition = "2018"

[dependencies]
tcx-chain = { path = "../tcx-chain" }
tcx-btc-fork = { path = "../tcx-btc-fork" }
bch_addr = "0.1.0"
bitcoin = "0.20.0"
secp256k1 = {version ="0.15", features = ["recovery"] }
tiny-bip39 = "0.6.0"
bitcoin_hashes = "0.7"
bitcoinconsensus = { version = "0.16", optional = true }
failure = "0.1.5"
hex = "0.3.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"