[package]
name = "tcx-tester"
version = "0.1.1"
authors = ["Neal Xu <imxuneal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.0"
tcx = { path = "../tcx" }
prost = "0.6.1"
bytes = "0.5.4"